from PyQt5 import QtCore, QtGui, QtWidgets


# Music editor form
class PianoForm(object):
    def setupUi(self, Form):
        self.setWindowTitle('Создание музыки')
        Form.setObjectName("Form")
        Form.resize(935, 369)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(750, 10, 131, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:red;\n""")
        self.radioButton.setObjectName("radioButton")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 40, 190))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: white;\n"
                                      "text-color: black;\n"
                                      "border: 2px solid black;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 40, 30, 190))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:black;\n"
                                        "color:white;\n"
                                        "border: 2px solid grey;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 30, 40, 190))
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: white;\n"
                                        "text-color: black;\n"
                                        "border: 2px solid black;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 40, 30, 190))
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:black;\n"
                                        "color:white;\n"
                                        "border: 2px solid grey;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 30, 40, 190))
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: white;\n"
                                        "text-color: black;\n"
                                        "border: 2px solid black;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 40, 30, 190))
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color:black;\n"
                                        "color:white;\n"
                                        "border: 2px solid grey;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 30, 40, 190))
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: white;\n"
                                        "text-color: black;\n"
                                        "border: 2px solid black;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 40, 30, 190))
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color:black;\n"
                                        "color:white;\n"
                                        "border: 2px solid grey;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 30, 40, 190))
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: white;\n"
                                        "text-color: black;\n"
                                        "border: 2px solid black;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(330, 40, 30, 190))
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color:black;\n"
                                         "color:white;\n"
                                         "border: 2px solid grey;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(360, 30, 40, 190))
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: white;\n"
                                         "text-color: black;\n"
                                         "border: 2px solid black;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(400, 40, 30, 190))
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color:black;\n"
                                         "color:white;\n"
                                         "border: 2px solid grey;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(430, 30, 40, 190))
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: white;\n"
                                         "text-color: black;\n"
                                         "border: 2px solid black;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(470, 40, 30, 190))
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color:black;\n"
                                         "color:white;\n"
                                         "border: 2px solid grey;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(500, 30, 40, 190))
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: white;\n"
                                         "text-color: black;\n"
                                         "border: 2px solid black;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 40, 30, 190))
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color:black;\n"
                                         "color:white;\n"
                                         "border: 2px solid grey;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(580, 40, 91, 81))
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: white;\n"
                                         "text-color: black;\n"
                                         "border-radius: 40px;\n"
                                         "border: 2px solid black;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(630, 130, 91, 81))
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: white;\n"
                                         "text-color: black;\n"
                                         "border-radius: 40px;\n"
                                         "border: 2px solid black;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(740, 0, 3, 400))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(650, 270, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("source/image/tarelki.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(15, 240, 30, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(86, 240, 31, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(156, 240, 31, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(225, 240, 40, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(290, 240, 50, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(367, 240, 30, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(437, 240, 30, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(40, 300, 50, 50))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("source/image/banjo.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(600, 220, 50, 50))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("source/image/baraban.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(110, 300, 50, 50))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("source/image/cello.png"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(180, 300, 50, 50))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("source/image/clarenet.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(250, 300, 50, 50))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("source/image/contrabass.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(320, 300, 50, 50))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("source/image/guitar.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(390, 300, 50, 50))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("source/image/rockguitar.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(460, 300, 50, 50))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("source/image/clarnet2.png"))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(500, 250, 50, 50))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("source/image/banjo2.png"))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(540, 300, 50, 50))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("source/image/cello2.png"))
        self.label_19.setObjectName("label_19")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(750, 90, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(750, 130, 170, 30))
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Музыкальный редактор"))
        self.radioButton.setText(_translate("Form", "Rec"))
        self.pushButton.setText(_translate("Form", "Q"))
        self.pushButton_2.setText(_translate("Form", "A"))
        self.pushButton_3.setText(_translate("Form", "W"))
        self.pushButton_4.setText(_translate("Form", "S"))
        self.pushButton_5.setText(_translate("Form", "E"))
        self.pushButton_6.setText(_translate("Form", "D"))
        self.pushButton_7.setText(_translate("Form", "R"))
        self.pushButton_8.setText(_translate("Form", "F"))
        self.pushButton_9.setText(_translate("Form", "T"))
        self.pushButton_10.setText(_translate("Form", "G"))
        self.pushButton_11.setText(_translate("Form", "Y"))
        self.pushButton_12.setText(_translate("Form", "H"))
        self.pushButton_13.setText(_translate("Form", "U"))
        self.pushButton_14.setText(_translate("Form", "J"))
        self.pushButton_15.setText(_translate("Form", "I"))
        self.pushButton_16.setText(_translate("Form", "K"))
        self.pushButton_17.setText(_translate("Form", "Z"))
        self.pushButton_18.setText(_translate("Form", "X"))
        self.label_3.setText(_translate("Form", "ДО"))
        self.label_4.setText(_translate("Form", "РЕ"))
        self.label_5.setText(_translate("Form", "МИ"))
        self.label_6.setText(_translate("Form", "ФА"))
        self.label_7.setText(_translate("Form", "СОЛЬ"))
        self.label_8.setText(_translate("Form", "ЛЯ"))
        self.label_9.setText(_translate("Form", "СИ"))
        self.pushButton_19.setText(_translate("Form", "Добавить в видео"))
        self.pushButton_20.setText(_translate("Form", "Сохранить"))


class PhotoEditorForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(941, 701)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(580, 0, 3, 570))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 570, 580, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(593, 20, 90, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 20, 90, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 20, 140, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 590, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(30, 630, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(84, 630, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(110, 630, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 660, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(240, 583, 3, 110))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 590, 300, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(Form)
        self.spinBox_3.setGeometry(QtCore.QRect(340, 630, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(Form)
        self.spinBox_4.setGeometry(QtCore.QRect(410, 630, 42, 22))
        self.spinBox_4.setFont(font)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(390, 630, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 660, 76, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(710, 70, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(580, 70, 360, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(590, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(720, 155, 140, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(590, 211, 101, 31))
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(720, 214, 140, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(590, 270, 81, 31))
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(720, 280, 140, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(590, 340, 111, 31))
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(720, 350, 140, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(590, 410, 111, 31))
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(720, 420, 140, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(593, 480, 111, 31))
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(722, 490, 140, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(710, 540, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(620, 590, 30, 30))
        self.pushButton_12.setStyleSheet("background-color:black;")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(670, 590, 100, 30))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(750, 650, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(620, 650, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(850, 590, 40, 40))
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(580, 580, 3, 110))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Фоторедактор"))
        self.pushButton.setText(_translate("Form", "Открыть"))
        self.pushButton_2.setText(_translate("Form", "Сохранить"))
        self.pushButton_3.setText(_translate("Form", "Добавить в видео"))
        self.label_2.setText(_translate("Form", "Создать изображение"))
        self.label_3.setText(_translate("Form", "x"))
        self.pushButton_4.setText(_translate("Form", "ОК"))
        self.label_4.setText(_translate("Form", "Изменить размеры изображения"))
        self.label_5.setText(_translate("Form", "x"))
        self.pushButton_5.setText(_translate("Form", "ОК"))
        self.label_6.setText(_translate("Form", "Фильтры"))
        self.label_7.setText(_translate("Form", "Чёрно-белый"))
        self.pushButton_6.setText(_translate("Form", "Применить"))
        self.label_8.setText(_translate("Form", "Контрастность"))
        self.pushButton_7.setText(_translate("Form", "Применить"))
        self.label_9.setText(_translate("Form", "Негатив"))
        self.pushButton_8.setText(_translate("Form", "Применить"))
        self.label_10.setText(_translate("Form", "Оттенки серого"))
        self.pushButton_9.setText(_translate("Form", "Применить"))
        self.label_11.setText(_translate("Form", "Сепия"))
        self.pushButton_10.setText(_translate("Form", "Применить"))
        self.label_12.setText(_translate("Form", "Контур"))
        self.pushButton_11.setText(_translate("Form", "Применить"))
        self.label_13.setText(_translate("Form", "Рисование"))
        self.pushButton_14.setText(_translate("Form", "Изменить цвет"))
        self.comboBox.setItemText(0, _translate("Form", "5"))
        self.comboBox.setItemText(1, _translate("Form", "1"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "8"))
        self.comboBox.setItemText(4, _translate("Form", "10"))
        self.label_14.setText(_translate("Form", "Размер кисти"))


class VideoEditorForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1110, 746)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("background-color:#d0eaf5;")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 800, 520))
        self.scrollArea.setStyleSheet("background-color:#b7db97;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 518))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(820, 10, 281, 192))
        self.tableWidget.setStyleSheet("background-color:white;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(820, 240, 221, 23))
        self.pushButton.setStyleSheet("background-color:white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 210, 220, 23))
        self.pushButton_2.setStyleSheet("background-color:white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1050, 240, 20, 23))
        self.pushButton_3.setStyleSheet("background-color:white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(820, 280, 281, 192))
        self.tableWidget_2.setStyleSheet("background-color:white;")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(820, 480, 220, 23))
        self.pushButton_4.setStyleSheet("background-color:white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 510, 221, 23))
        self.pushButton_5.setStyleSheet("background-color:white;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(1050, 510, 20, 23))
        self.pushButton_6.setStyleSheet("background-color:white;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(20, 630, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color:#d0eaf5;")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 670, 550, 30))
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color:#d0eaf5;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 630, 140, 30))
        self.pushButton_8.setStyleSheet("background-color:white;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 580, 160, 31))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(180, 580, 51, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 570, 240, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 620, 260, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 710, 310, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 700, 280, 23))
        self.pushButton_7.setStyleSheet("background-color:white;")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Видеоредактор"))
        self.pushButton.setText(_translate("Form", "Добавить сохранённые изображения"))
        self.pushButton_2.setText(_translate("Form", "Загрузить изображение"))
        self.pushButton_3.setText(_translate("Form", "с"))
        self.pushButton_4.setText(_translate("Form", "Загрузить музыку"))
        self.pushButton_5.setText(_translate("Form", "Добавить сохранённую музыку"))
        self.pushButton_6.setText(_translate("Form", "c"))
        self.radioButton.setText(_translate("Form", "Увеличение изображений  в соответствие  максимальным размерам"))
        self.radioButton_2.setText(_translate("Form", "Уменьшение изображений  в соответствие минимальным размерам"))
        self.pushButton_8.setText(_translate("Form", "Выбрать цвет фона"))
        self.label.setText(_translate("Form", "Кадров в секунду"))
        self.pushButton_7.setText(_translate("Form", "Сохранить"))
